import type { Metadata } from "next";
import { Reem_Kufi } from "next/font/google";
import "./globals.css";

const reemKufi = Reem_Kufi({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-reem-kufi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={reemKufi.variable}>{children}</body>
    </html>
  );
}
